Productcard traceability fields
altairisfr/dolibarr pull request #10
Opened 2021-05-05 14:28 UTC by altairis-noe

# Première partie
traitement des champs de traçabilité dans product/stock/card.php

2021-05-05 15:52 UTC, altairis-tof requested changes

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/card.php
> +							$mask = !empty($object->batch_mask) ? $object->batch_mask : $conf->global->LOT_ADVANCED_MASK;
mets un espace entre ! et empty spt (sinon eldy donner fessée)

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/card.php
> +							$mask = !empty($object->batch_mask) ? $object->batch_mask : $conf->global->SN_ADVANCED_MASK;
idem

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/card.php
> +			if (empty($conf->global->PRODUCT_DISABLE_TRACEABILITY)) {
if ( empty($conf->global->PRODUCT_DISABLE_TRACEABILITY) ) {

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/card.php
> +			if (empty($conf->global->PRODUCT_DISABLE_TRACEABILITY)) {
il faut des espaces sinon panpan cucul

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/card.php
> +			if (empty($conf->global->PRODUCT_DISABLE_TRACEABILITY)) {
idem

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/class/html.formproduct.class.php
> +     *  @param	array	$events					Event options to run on change. Example: array(array('method'=>'getContacts', 'url'=>dol_buildpath('/core/ajax/contacts.php',1), 'htmlname'=>'contactid', 'params'=>ar
c'est du copier/coller toujours d'actualité dans cette fonction ??? (j'en sais rien)

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/stock/class/productlot.class.php
> +		// 'fk_qcstatus'        => array('type'=>'varchar(6)', 'label'=>'Status', 'enabled'=>'empty($conf->global->PRODUCT_DISABLE_TRACEABILITY)?1:0', 'visible'=>5, 'position'=>120),
no comment ;) enfin si enlève carrément la ligne

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/stock/class/productlot.class.php
> +		// $sql .= ' '.(!isset($this->fk_qcstatus) || dol_strlen($this->fk_qcstatus) == 0 ? 'NULL' : $this->fk_qcstatus).',';
no comment ;) enfin si enlève carrément la ligne

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/stock/class/productlot.class.php
> +		// $sql .= " t.fk_qcstatus,";
no comment ;) enfin si enlève carrément la ligne

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/stock/class/productlot.class.php
> +		// $sql .= ' fk_qcstatus = '.(!isset($this->fk_qcstatus) || dol_strlen($this->fk_qcstatus) != 0 ? "'".$this->db->escape($this->fk_qcstatus)."'" : 'null').',';
no comment ;) enfin si enlève carrément la ligne

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/stock/productlot_card.php
> +	if ($action == 'seteatby' && $user->rights->stock->creer && !GETPOST('cancel', 'alpha')) {
attention aux espaces
if ( $action == 'seteatby' && $user->rights->stock->creer && ! GETPOST('cancel', 'alpha') ) {

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/stock/productlot_card.php
> +	if ($action == 'setsellby' && $user->rights->stock->creer && !GETPOST('cancel', 'alpha')) {
idem

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/stock/productlot_card.php
> +	if ($action == 'seteol_date' && $user->rights->stock->creer && !GETPOST('cancel', 'alpha')) {
idem

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/stock/productlot_card.php
> +	if ($action == 'setmanufacturing_date' && $user->rights->stock->creer && !GETPOST('cancel', 'alpha')) {
idem

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/stock/productlot_card.php
> +	if ($action == 'setscrapping_date' && $user->rights->stock->creer && !GETPOST('cancel', 'alpha')) {
idem

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/stock/productlot_card.php
> +	if ($action == 'setcommissionning_date' && $user->rights->stock->creer && !GETPOST('cancel', 'alpha')) {
idem

2021-05-05 15:52 UTC, altairis-tof commented on htdocs/product/stock/productlot_card.php
> +	if ($action == 'setqc_frequency' && $user->rights->stock->creer && !GETPOST('cancel', 'alpha')) {
idem

2021-05-06 07:38 UTC, altairis-noe commented on htdocs/product/card.php
> +			if (empty($conf->global->PRODUCT_DISABLE_TRACEABILITY)) {
C’est curieux, cette histoires d’espaces, parce qu’il n’y en a clairement pas partout…

2021-05-06 07:40 UTC, altairis-tof commented on htdocs/product/card.php
> +			if (empty($conf->global->PRODUCT_DISABLE_TRACEABILITY)) {
oui y en avait pas avant... je crois que c'est même stickler qui nous y oblige.

2021-05-06 07:40 UTC, altairis-tof commented on htdocs/product/card.php
> +			if (empty($conf->global->PRODUCT_DISABLE_TRACEABILITY)) {
(y avait pas stickler avant...)

2021-05-06 07:45 UTC, altairis-noe commented on htdocs/product/class/html.formproduct.class.php
> +     *  @param	array	$events					Event options to run on change. Example: array(array('method'=>'getContacts', 'url'=>dol_buildpath('/core/ajax/contacts.php',1), 'htmlname'=>'contactid', 'params'=>ar
J’ai effectivement copié la fonction à partir d’un autre modèle de select. Pour l’usage qu’on en a, effectivement, les events ne sont peut-être pas nécessaires, je regarde.

2021-05-06 07:49 UTC, altairis-noe commented on htdocs/product/class/html.formproduct.class.php
> +     *  @param	array	$events					Event options to run on change. Example: array(array('method'=>'getContacts', 'url'=>dol_buildpath('/core/ajax/contacts.php',1), 'htmlname'=>'contactid', 'params'=>ar
les events sont renvoyés à l’ajax_combobox, je pense laisser cette possibilité pour l’instant… mais pas dans cette branche

2021-05-06 09:54 UTC, altairis-noe commented
closes altairisfr/COPAC-LOC-0.0.1-Socle#26

2021-05-06 12:36 UTC, merged